### ISSUE TITLE
Loading failed for the module with source “c:/SKLEARN/node_modules/sklearn”. in simple local nodejs setup

### ISSUE THREAD

**Issue by LSW1980** [transitive-bullshit/scikit-learn-ts#5]
I try a simple html file included with script tag module using your https://sklearn.vercel.app/guide/usage example and get a error:

Loading failed for the module with source “c:/SKLEARN/node_modules/sklearn”.
(I use vscode and look like it recognize as : module "c:/SKLEARN/node_modules/sklearn/build/index" , when hover mouse over)

Then I run usage example with node.exe example.js (convert import to require) still get error;

Error: Cannot find module 'C:/SKLEARN/node_modules/sklearn'

-----

Would you provide a completely working example in a zip-file with all the directories and files like package.json, etc ... that way we know for sure at least one way is working.

Also, are you going to provide a global variable like sklearn then in browser console we can access to all its functions/modules just like d3.js or tensorflow.js. What about one script tag file in html (as d3.js or tensorflow.js has been using)

Thank you

**Comment by transitive-bullshit** [comment]
This module is node.js, server-side only since it invokes python under the hood. Therefore, it will not work in the browser.
