### ISSUE TITLE
Cannot change the ESM format to Common JS for this package

### ISSUE THREAD

**Issue by Gigme18** [transitive-bullshit/scikit-learn-ts#7]
Error [ERR_REQUIRE_ESM]: require() of ES Module node_module/sklearn/build/index.js from mypath:index.js not supported.
Instead change the require of mypath:index.js in mypath:index.js to a dynamic import() which is available in all CommonJS modules.

**Comment by transitive-bullshit** [comment]
See https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c
