### ISSUE TITLE
"'generator' object has no attribute '__dict__'"

### ISSUE THREAD

**Issue by Gigme18** [transitive-bullshit/scikit-learn-ts#8]
When I am calling GroupkFold.split()

I am getting an error:

error: undefined,
  exception: {
    type: { name: 'AttributeError', module: 'builtins' },
    message: "'generator' object has no attribute '__dict__'",
    args: [ "'generator' object has no attribute '__dict__'" ],
    format: [
      "AttributeError: 'generator' object has no attribute '__dict__'\n"
    ]

  traceback: {
    lineno: 111,
    strack: [
      '  File "node_modules\\@fisch0920\\python-bridge\\node_python_bridge.py", line 114, in <module>\n' +
        "    response = dict(type='exception', value=format_exception(t, e, tb))\n"
    ],
    format: [
      '  File "..\\node_modules\\@fisch0920\\python-bridge\\node_python_bridge.py", line 111, in <module>\n' +
        "    response = dict(type='success', value=json.dumps(value, separators=(',', ':'), cls=JavaScriptEncoder))\n",
      '  File "Programs\\Python\\Python310\\lib\\json\\__init__.py", line 238, in dumps\n' +   
        '    **kw).encode(obj)\n',
      '  File "Programs\\Python\\Python310\\lib\\json\\encoder.py", line 199, in encode\n' +   
        '    chunks = self.iterencode(o, _one_shot=True)\n',
      '  File "Python\\Python310\\lib\\json\\encoder.py", line 257, in iterencode\n' 
+
        '    return _iterencode(o, 0)\n',
      '  File "node_modules\\@fisch0920\\python-bridge\\node_python_bridge.py", line 81, in default\n' +
        '    return o.__dict__\n'
    ]
  }, 

I am confused why this error is triggered.

**Comment by Podolchak** [comment]
Same error
